# Generated by Django 5.2.8 on 2026-01-12 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
        ('course', '0002_remove_courseinfo_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='course_type',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='initial_price',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='monthly_duration',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='price',
        ),
        migrations.AddField(
            model_name='contract',
            name='course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course.courseinfo'),
            preserve_default=False,
        ),
    ]
