# Generated by Django 5.2.8 on 2026-01-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_remove_contract_contract_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
