# Generated by Django 5.2.8 on 2026-01-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_contract_contract_number_contract_initial_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='full_name',
        ),
        migrations.AddField(
            model_name='contract',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
