# Generated by Django 5.2.8 on 2026-01-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('salary_middle', models.CharField(max_length=500)),
            ],
        ),
    ]
