# Generated by Django 5.2.8 on 2026-01-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_courseinfo_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='contract_number',
        ),
    ]
