# Generated by Django 5.2.8 on 2026-01-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_courseinfo_contract_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfo',
            name='initial_price',
        ),
    ]
